name: Add Numbers in Python

on:
  push:
    branches:
      - main

jobs:
  add_numbers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add Numbers in Python
        run: |
          python - <<EOF
          number1 = 5
          number2 = 7
          sum = number1 + number2
          print(f"The sum of {number1} and {number2} is {sum}")
          EOF
