name: Add Numbers in Python

on:
  push:
    branches:
      - main

jobs:
  add_numbers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add Numbers in Python
        run: 
          print(f"The sum of {1} and {2} is {2+ 1}")
         
